-- Seed regions (Kolada muni type=L)
insert into vantetid.regions (id, slug, name, short_name, display_order) values
('0000','riket','Riket','Riket',0),
('0001','stockholm','Region Stockholm','Stockholm',10),
('0003','uppsala','Region Uppsala','Uppsala',20),
('0004','sormland','Region Sörmland','Sörmland',30),
('0005','ostergotland','Region Östergötland','Östergötland',40),
('0006','jonkoping','Region Jönköpings län','Jönköping',50),
('0007','kronoberg','Region Kronoberg','Kronoberg',60),
('0008','kalmar','Region Kalmar','Kalmar',70),
('0009','gotland','Region Gotland','Gotland',80),
('0010','blekinge','Region Blekinge','Blekinge',90),
('0012','skane','Region Skåne','Skåne',100),
('0013','halland','Region Halland','Halland',110),
('0014','vastra-gotaland','Västra Götalandsregionen','Västra Götaland',120),
('0017','varmland','Region Värmland','Värmland',130),
('0018','orebro','Region Örebro län','Örebro',140),
('0019','vastmanland','Region Västmanland','Västmanland',150),
('0020','dalarna','Region Dalarna','Dalarna',160),
('0021','gavleborg','Region Gävleborg','Gävleborg',170),
('0022','vasternorrland','Region Västernorrland','Västernorrland',180),
('0023','jamtland','Region Jämtland Härjedalen','Jämtland Härjedalen',190),
('0024','vasterbotten','Region Västerbotten','Västerbotten',200),
('0025','norrbotten','Region Norrbotten','Norrbotten',210)
on conflict (id) do nothing;

insert into vantetid.sources (slug, name, homepage_url, license, attribution, notes) values
('kolada','Kolada (RKA)','https://www.kolada.se','CC BY 4.0','Källa: Rådet för främjande av kommunala analyser (RKA) via Kolada','Kolada v3 REST-API.'),
('socialstyrelsen-pxweb','Socialstyrelsen statistikdatabas','https://px.socialstyrelsen.se','Socialstyrelsens öppna data','Källa: Socialstyrelsen','PxWeb API.'),
('skr-vantetider','Väntetider i vården (SKR)','https://www.vantetider.se','Fri användning med attribution','Källa: Väntetider i vården, SKR','Parallell rapportering till SKR:s väntetidsdatabas pågår under 2026.'),
('dataportal','Sveriges dataportal','https://www.dataportal.se','CC0 (katalogmetadata)','Källa: Sveriges dataportal','Används för att upptäcka nya regionala dataset.'),
('rcc-svf','Regionala cancercentrum (SVF)','https://cancercentrum.se','Fri användning med attribution','Källa: Regionala cancercentrum i samverkan','SVF-ledtider per diagnos.')
on conflict (slug) do nothing;

with s as (select id from vantetid.sources where slug = 'kolada')
insert into vantetid.metrics (slug, name_sv, short_name_sv, description_sv, unit, category, better_direction, source_id, source_kpi_id, source_url_template, target_value, display_order)
select * from (values
('specialist-forsta-kontakt-vantande-median',
 'Väntetid till första kontakt i specialiserad vård (väntande, median)',
 'Specialistvård — väntande',
 'Medianvärde för väntetid i dagar för de som väntar på första kontakt i specialiserad vård. Vårdgarantin är 90 dagar.',
 'days','specialist','lower',(select id from s),'N79240',
 'https://api.kolada.se/v3/data/kpi/N79240/municipality/{region}',90::numeric,10),
('specialist-forsta-kontakt-genomforda-median',
 'Väntetid till första kontakt i specialiserad vård (genomförda, median)',
 'Specialistvård — genomförda',
 'Medianvärde för antalet dagar patienter faktiskt fick vänta till sitt första besök i specialiserad vård.',
 'days','specialist','lower',(select id from s),'N79241',
 'https://api.kolada.se/v3/data/kpi/N79241/municipality/{region}',90::numeric,20),
('operation-vantande-median',
 'Väntetid till operation/åtgärd (väntande, median)',
 'Operation — väntande',
 'Medianvärde för väntetid i dagar för de som väntar på operation eller åtgärd i specialiserad vård.',
 'days','operation','lower',(select id from s),'N79242',
 'https://api.kolada.se/v3/data/kpi/N79242/municipality/{region}',90::numeric,30),
('operation-genomforda-median',
 'Väntetid till operation/åtgärd (genomförda, median)',
 'Operation — genomförda',
 'Medianvärde för antalet dagar patienter faktiskt fick vänta till operation eller åtgärd.',
 'days','operation','lower',(select id from s),'N79243',
 'https://api.kolada.se/v3/data/kpi/N79243/municipality/{region}',90::numeric,40),
('bup-forsta-besok-inom-90-dagar',
 'Första BUP-besök inom 90 dagar, andel (%)',
 'BUP — första besök i tid',
 'Andelen första besök i planerad barn- och ungdomspsykiatri som genomfördes inom 90 dagar från beslut om vård.',
 'percent','bup','higher',(select id from s),'U72552',
 'https://api.kolada.se/v3/data/kpi/U72552/municipality/{region}',100::numeric,50),
('bup-utredning-behandling-inom-30-dagar',
 'Startade BUP-utredningar/behandlingar inom 30 dagar, andel (%)',
 'BUP — start i tid',
 'Andelen utredningar och behandlingar som startats inom 30 dagar i barn- och ungdomspsykiatri.',
 'percent','bup','higher',(select id from s),'U79119',
 'https://api.kolada.se/v3/data/kpi/U79119/municipality/{region}',100::numeric,60),
('upplevd-vantetid-sjukhus',
 'Rimlig väntetid till sjukhusvård, andel (%)',
 'Upplevd väntetid sjukhus',
 'Andelen invånare som anser att väntetider till besök och behandling på sjukhus är rimliga. Källa: Hälso- och sjukvårdsbarometern.',
 'percent','perception','higher',(select id from s),'U70448',
 'https://api.kolada.se/v3/data/kpi/U70448/municipality/{region}',null::numeric,70),
('upplevd-vantetid-vardcentral',
 'Rimlig väntetid till vård-/hälsocentral, andel (%)',
 'Upplevd väntetid vårdcentral',
 'Andelen invånare som anser att väntetider till besök och behandling på vård- eller hälsocentral är rimliga.',
 'percent','perception','higher',(select id from s),'U70450',
 'https://api.kolada.se/v3/data/kpi/U70450/municipality/{region}',null::numeric,80),
('prostatacancer-pad-11d',
 'Väntetid till prostatacancerbesked, andel (%)',
 'Prostata — PAD i tid',
 'Andelen män som fått PAD-besked (diagnosbesked) inom 11 dagar efter utförd prostatabiopsi.',
 'percent','cancer','higher',(select id from s),'N70619',
 'https://api.kolada.se/v3/data/kpi/N70619/municipality/{region}',100::numeric,90),
('prostatacancer-forsta-besok-14d',
 'Väntetid till första besök vid misstänkt prostatacancer, andel (%)',
 'Prostata — första besök i tid',
 'Andelen män med misstänkt prostatacancer som fått nybesök på specialistklinik inom 14 dagar efter remissankomst.',
 'percent','cancer','higher',(select id from s),'N70620',
 'https://api.kolada.se/v3/data/kpi/N70620/municipality/{region}',100::numeric,100),
('bup-vardplatser-per-1000',
 'Disponibla BUP-vårdplatser per 1 000 invånare',
 'BUP — vårdplatser',
 'Antal disponibla vårdplatser inom barn- och ungdomspsykiatri dividerat med antal invånare (tusental).',
 'per_1000','capacity','higher',(select id from s),'N74816',
 'https://api.kolada.se/v3/data/kpi/N74816/municipality/{region}',null::numeric,110)
) as t(slug,name_sv,short_name_sv,description_sv,unit,category,better_direction,source_id,source_kpi_id,source_url_template,target_value,display_order)
on conflict (slug) do nothing;
